[tool.poetry]
name = "PyCricForecast"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.1.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
